services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - docsmate-network
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - db_data:/app/data/db
      - faiss_data:/app/faiss_index

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8501:8501"
    networks:
      - docsmate-network
    depends_on:
      - backend

  ollama:
    image: ollama/ollama
    container_name: docsmate-ollama
    volumes:
      - ./ollama-data:/root/.ollama
    networks:
      - docsmate-network

networks:
  docsmate-network:
    driver: bridge

volumes:
  db_data:
  faiss_data:
